// SPDX-License-Identifier: AGPL-3.0-or-later

//! True multi-shift CG: shared Krylov basis across all shifts.
//!
//! Solves (D†D + σ_s) x_s = b for all shifts s simultaneously using
//! a single Krylov subspace generated by D†D. Only ONE matrix-vector
//! product (D†D · p) per iteration instead of N_shifts, reducing the
//! dominant compute cost by a factor of N_shifts.
//!
//! Algorithm: Jegerlehner (hep-lat/9612014), adapted for GPU-resident
//! scalars with exponential back-off convergence checking.
//!
//! Per iteration:
//!   1. q = D†D · p_base                    (2 Dirac passes — shared)
//!   2. α₀ = ρ / ⟨p|q⟩                     (dot + reduce + scalar)
//!   3. ζ recurrence for all shifts          (1 workgroup, tiny)
//!   4. x_s += α_s · p_s for each shift     (N_shifts vector updates)
//!   5. r -= α₀ · q, x_base += α₀ · p_base (base xr update)
//!   6. ρ_new = ⟨r|r⟩                       (dot + reduce)
//!   7. β = ρ_new / ρ                        (scalar)
//!   8. p_base = r + β · p_base             (base p update)
//!   9. p_s = ζ_s · r + β_s · p_s           (N_shifts vector updates)

use super::dynamical::{GpuDynHmcPipelines, GpuDynHmcState};
use super::resident_cg_buffers::{ReduceChain, build_reduce_chain_pub, encode_reduce_chain};
use super::resident_cg_pipelines::GpuResidentCgPipelines;
use super::{GpuF64, make_u32x4_params};

const WGSL_MS_ZETA: &str = include_str!("../shaders/ms_zeta_update_f64.wgsl");
const WGSL_MS_X_UPDATE: &str = include_str!("../shaders/ms_x_update_f64.wgsl");
const WGSL_MS_P_UPDATE: &str = include_str!("../shaders/ms_p_update_f64.wgsl");
const WGSL_CG_ALPHA_SHIFTED: &str = include_str!("../shaders/cg_compute_alpha_shifted_f64.wgsl");
const WGSL_CG_XR_SHIFTED: &str = include_str!("../shaders/cg_update_xr_shifted_f64.wgsl");

const CG_BACKOFF_CAP: usize = 2000;

/// Pipelines for true multi-shift CG.
pub struct TrueMultiShiftPipelines {
    /// Base CG pipelines (beta, p update, reduce — alpha/xr replaced by shifted versions).
    pub base: GpuResidentCgPipelines,
    /// Shifted alpha: α = rz / (pAp + σ_min · pp).
    pub shifted_alpha_pipeline: wgpu::ComputePipeline,
    /// Shifted xr update: r -= α · (ap + σ_min · p).
    pub shifted_xr_pipeline: wgpu::ComputePipeline,
    /// ζ recurrence + shifted scalar computation.
    pub zeta_pipeline: wgpu::ComputePipeline,
    /// Shifted x update: x_σ += α_σ · p_σ.
    pub ms_x_pipeline: wgpu::ComputePipeline,
    /// Shifted p update: p_σ = ζ_σ · r + β_σ · p_σ.
    pub ms_p_pipeline: wgpu::ComputePipeline,
}

impl TrueMultiShiftPipelines {
    #[must_use]
    pub fn new(gpu: &GpuF64) -> Self {
        Self {
            base: GpuResidentCgPipelines::new(gpu),
            shifted_alpha_pipeline: gpu
                .create_pipeline_f64(WGSL_CG_ALPHA_SHIFTED, "ms_alpha_shifted"),
            shifted_xr_pipeline: gpu.create_pipeline_f64(WGSL_CG_XR_SHIFTED, "ms_xr_shifted"),
            zeta_pipeline: gpu.create_pipeline_f64(WGSL_MS_ZETA, "ms_zeta"),
            ms_x_pipeline: gpu.create_pipeline_f64(WGSL_MS_X_UPDATE, "ms_x_update"),
            ms_p_pipeline: gpu.create_pipeline_f64(WGSL_MS_P_UPDATE, "ms_p_update"),
        }
    }
}

/// GPU buffers for true multi-shift CG.
pub struct TrueMultiShiftBuffers {
    pub p_shift_bufs: Vec<wgpu::Buffer>,
    pub zeta_curr_buf: wgpu::Buffer,
    pub zeta_prev_buf: wgpu::Buffer,
    pub alpha_s_buf: wgpu::Buffer,
    pub beta_ratio_buf: wgpu::Buffer,
    pub sigma_buf: wgpu::Buffer,
    pub zeta_params_buf: wgpu::Buffer,
    pub rz_buf: wgpu::Buffer,
    pub rz_new_buf: wgpu::Buffer,
    pub pap_buf: wgpu::Buffer,
    pub pp_buf: wgpu::Buffer,
    pub sigma_min_buf: wgpu::Buffer,
    pub alpha_buf: wgpu::Buffer,
    pub beta_buf: wgpu::Buffer,
    pub alpha_prev_buf: wgpu::Buffer,
    pub beta_prev_buf: wgpu::Buffer,
    pub scratch_a: wgpu::Buffer,
    pub scratch_b: wgpu::Buffer,
    pub reduce_to_pap: ReduceChain,
    pub reduce_to_pp: ReduceChain,
    pub reduce_to_rz: ReduceChain,
    pub reduce_to_rz_new: ReduceChain,
    pub convergence_staging: wgpu::Buffer,
    pub dirac_d_bg: wgpu::BindGroup,
    pub dirac_ddag_bg: wgpu::BindGroup,
    pub dot_pap_bg: wgpu::BindGroup,
    pub dot_pp_bg: wgpu::BindGroup,
    pub dot_rr_bg: wgpu::BindGroup,
    pub compute_alpha_bg: wgpu::BindGroup,
    pub compute_beta_bg: wgpu::BindGroup,
    pub update_xr_bg: wgpu::BindGroup,
    pub update_p_bg: wgpu::BindGroup,
    pub zeta_bg: wgpu::BindGroup,
    pub ms_p_bgs: Vec<wgpu::BindGroup>,
    pub xr_params_buf: wgpu::Buffer,
    pub p_params_buf: wgpu::Buffer,
    pub wg_dirac: u32,
    pub wg_dot: u32,
    pub wg_vec: u32,
    pub n_shifts: usize,
    pub n_flat: usize,
}

fn make_dirac_bg(
    gpu: &GpuF64,
    dirac_pl: &wgpu::ComputePipeline,
    state: &GpuDynHmcState,
    input: &wgpu::Buffer,
    output: &wgpu::Buffer,
    hop_sign: f64,
) -> wgpu::BindGroup {
    let vol = state.gauge.volume;
    let mut params = Vec::with_capacity(24);
    params.extend_from_slice(&(vol as u32).to_le_bytes());
    params.extend_from_slice(&0u32.to_le_bytes());
    params.extend_from_slice(&state.mass.to_le_bytes());
    params.extend_from_slice(&hop_sign.to_le_bytes());
    let pbuf = gpu.create_uniform_buffer(&params, "ms_dirac_p");
    gpu.create_bind_group(
        dirac_pl,
        &[
            &pbuf,
            &state.gauge.link_buf,
            input,
            output,
            &state.gauge.nbr_buf,
            &state.phases_buf,
        ],
    )
}

impl TrueMultiShiftBuffers {
    /// Allocate multi-shift CG buffers for `n_shifts` shifts.
    #[must_use]
    pub fn new(
        gpu: &GpuF64,
        dyn_pipelines: &GpuDynHmcPipelines,
        ms_pipelines: &TrueMultiShiftPipelines,
        state: &GpuDynHmcState,
        n_shifts: usize,
    ) -> Self {
        let vol = state.gauge.volume;
        let n_flat = vol * 6;
        let n_pairs = vol * 3;

        let max_wg = n_pairs.div_ceil(256);
        let scratch_a = gpu.create_f64_output_buffer(max_wg.max(1), "ms_scratch_a");
        let scratch_b = gpu.create_f64_output_buffer(max_wg.max(1), "ms_scratch_b");

        let p_shift_bufs: Vec<_> = (0..n_shifts)
            .map(|s| gpu.create_f64_output_buffer(n_flat, &format!("ms_p_{s}")))
            .collect();

        let zeta_curr_buf = gpu.create_f64_output_buffer(n_shifts, "ms_zeta_curr");
        let zeta_prev_buf = gpu.create_f64_output_buffer(n_shifts, "ms_zeta_prev");
        let alpha_s_buf = gpu.create_f64_output_buffer(n_shifts, "ms_alpha_s");
        let beta_ratio_buf = gpu.create_f64_output_buffer(n_shifts, "ms_beta_ratio");
        let sigma_buf = gpu.create_f64_output_buffer(n_shifts, "ms_sigma");
        let zeta_params = make_u32x4_params(n_shifts as u32);
        let zeta_params_buf = gpu.create_uniform_buffer(&zeta_params, "ms_zeta_params");

        let rz_buf = gpu.create_f64_output_buffer(1, "ms_rz");
        let rz_new_buf = gpu.create_f64_output_buffer(1, "ms_rz_new");
        let pap_buf = gpu.create_f64_output_buffer(1, "ms_pap");
        let pp_buf = gpu.create_f64_output_buffer(1, "ms_pp");
        let sigma_min_buf = gpu.create_f64_output_buffer(1, "ms_sigma_min");
        let alpha_buf = gpu.create_f64_output_buffer(1, "ms_alpha");
        let beta_buf = gpu.create_f64_output_buffer(1, "ms_beta");
        let alpha_prev_buf = gpu.create_f64_output_buffer(1, "ms_alpha_prev");
        let beta_prev_buf = gpu.create_f64_output_buffer(1, "ms_beta_prev");

        let convergence_staging = gpu.create_staging_buffer(8, "ms_conv_staging");

        // Reduce chains for dot products → scalar accumulators
        let reduce_to_pap = build_reduce_chain_pub(
            gpu,
            &ms_pipelines.base.reduce_pipeline,
            &state.dot_buf,
            &scratch_a,
            &scratch_b,
            &pap_buf,
            n_pairs,
        );
        let reduce_to_pp = build_reduce_chain_pub(
            gpu,
            &ms_pipelines.base.reduce_pipeline,
            &state.dot_buf,
            &scratch_a,
            &scratch_b,
            &pp_buf,
            n_pairs,
        );
        let reduce_to_rz = build_reduce_chain_pub(
            gpu,
            &ms_pipelines.base.reduce_pipeline,
            &state.dot_buf,
            &scratch_a,
            &scratch_b,
            &rz_buf,
            n_pairs,
        );
        let reduce_to_rz_new = build_reduce_chain_pub(
            gpu,
            &ms_pipelines.base.reduce_pipeline,
            &state.dot_buf,
            &scratch_a,
            &scratch_b,
            &rz_new_buf,
            n_pairs,
        );

        // Dirac: D·p → temp, D†·temp → ap
        let dirac_d_bg = make_dirac_bg(
            gpu,
            &dyn_pipelines.dirac_pipeline,
            state,
            &state.p_buf,
            &state.temp_buf,
            1.0,
        );
        let dirac_ddag_bg = make_dirac_bg(
            gpu,
            &dyn_pipelines.dirac_pipeline,
            state,
            &state.temp_buf,
            &state.ap_buf,
            -1.0,
        );

        // Dot products: <p|ap>, <p|p>, <r|r>
        let dot_params = make_u32x4_params(n_pairs as u32);
        let dot_pap_pbuf = gpu.create_uniform_buffer(&dot_params, "ms_dot_pap_p");
        let dot_pap_bg = gpu.create_bind_group(
            &dyn_pipelines.dot_pipeline,
            &[&dot_pap_pbuf, &state.p_buf, &state.ap_buf, &state.dot_buf],
        );
        let dot_pp_pbuf = gpu.create_uniform_buffer(&dot_params, "ms_dot_pp_p");
        let dot_pp_bg = gpu.create_bind_group(
            &dyn_pipelines.dot_pipeline,
            &[&dot_pp_pbuf, &state.p_buf, &state.p_buf, &state.dot_buf],
        );
        let dot_rr_pbuf = gpu.create_uniform_buffer(&dot_params, "ms_dot_rr_p");
        let dot_rr_bg = gpu.create_bind_group(
            &dyn_pipelines.dot_pipeline,
            &[&dot_rr_pbuf, &state.r_buf, &state.r_buf, &state.dot_buf],
        );

        // Shifted alpha: α = rz / (pAp + σ_min · pp)
        let compute_alpha_bg = gpu.create_bind_group(
            &ms_pipelines.shifted_alpha_pipeline,
            &[&rz_buf, &pap_buf, &pp_buf, &sigma_min_buf, &alpha_buf],
        );
        let compute_beta_bg = gpu.create_bind_group(
            &ms_pipelines.base.compute_beta_pipeline,
            &[&rz_new_buf, &rz_buf, &beta_buf],
        );

        // Shifted xr update: r -= α · (ap + σ_min · p)
        let xr_params = make_u32x4_params(n_flat as u32);
        let xr_params_buf = gpu.create_uniform_buffer(&xr_params, "ms_xr_p");
        let update_xr_bg = gpu.create_bind_group(
            &ms_pipelines.shifted_xr_pipeline,
            &[
                &xr_params_buf,
                &state.x_buf,
                &state.r_buf,
                &state.p_buf,
                &state.ap_buf,
                &alpha_buf,
                &sigma_min_buf,
            ],
        );
        let p_params = make_u32x4_params(n_flat as u32);
        let p_params_buf = gpu.create_uniform_buffer(&p_params, "ms_p_p");
        let update_p_bg = gpu.create_bind_group(
            &ms_pipelines.base.update_p_pipeline,
            &[&p_params_buf, &state.p_buf, &state.r_buf, &beta_buf],
        );

        let wg_dirac = (vol as u32).div_ceil(64);
        let wg_dot = (n_pairs as u32).div_ceil(64);
        let wg_vec = (n_flat as u32).div_ceil(64);

        // Pre-create bind groups for per-shift operations (avoid allocation in hot loop)
        let zeta_bg = gpu.create_bind_group(
            &ms_pipelines.zeta_pipeline,
            &[
                &zeta_params_buf,
                &sigma_buf,
                &zeta_curr_buf,
                &zeta_prev_buf,
                &alpha_s_buf,
                &beta_ratio_buf,
                &alpha_buf,
                &beta_prev_buf,
                &alpha_prev_buf,
            ],
        );

        let ms_p_bgs: Vec<_> = (0..n_shifts)
            .map(|s| {
                let mut params = [0u32; 4];
                params[0] = n_flat as u32;
                params[1] = s as u32;
                let pbuf =
                    gpu.create_uniform_buffer(bytemuck::cast_slice(&params), &format!("ms_pu_{s}"));
                gpu.create_bind_group(
                    &ms_pipelines.ms_p_pipeline,
                    &[
                        &pbuf,
                        &p_shift_bufs[s],
                        &state.r_buf,
                        &zeta_curr_buf,
                        &beta_ratio_buf,
                        &beta_buf,
                    ],
                )
            })
            .collect();

        Self {
            p_shift_bufs,
            zeta_curr_buf,
            zeta_prev_buf,
            alpha_s_buf,
            beta_ratio_buf,
            sigma_buf,
            zeta_params_buf,
            rz_buf,
            rz_new_buf,
            pap_buf,
            pp_buf,
            sigma_min_buf,
            alpha_buf,
            beta_buf,
            alpha_prev_buf,
            beta_prev_buf,
            scratch_a,
            scratch_b,
            reduce_to_pap,
            reduce_to_pp,
            reduce_to_rz,
            reduce_to_rz_new,
            convergence_staging,
            dirac_d_bg,
            dirac_ddag_bg,
            dot_pap_bg,
            dot_pp_bg,
            dot_rr_bg,
            compute_alpha_bg,
            compute_beta_bg,
            update_xr_bg,
            update_p_bg,
            zeta_bg,
            ms_p_bgs,
            xr_params_buf,
            p_params_buf,
            wg_dirac,
            wg_dot,
            wg_vec,
            n_shifts,
            n_flat,
        }
    }
}

/// Encode one batch of true multi-shift CG iterations.
///
/// All bind groups are pre-created: `ms_x_bgs` for per-shift x-updates (created per-solve
/// since they depend on the caller's `x_bufs`), and `bufs.zeta_bg` / `bufs.ms_p_bgs` from
/// the buffer struct.
fn encode_ms_cg_batch(
    enc: &mut wgpu::CommandEncoder,
    dyn_pipelines: &GpuDynHmcPipelines,
    ms_pipelines: &TrueMultiShiftPipelines,
    bufs: &TrueMultiShiftBuffers,
    ms_x_bgs: &[wgpu::BindGroup],
    batch: usize,
) {
    for _ in 0..batch {
        GpuF64::encode_pass(
            enc,
            &dyn_pipelines.dirac_pipeline,
            &bufs.dirac_d_bg,
            bufs.wg_dirac,
        );
        GpuF64::encode_pass(
            enc,
            &dyn_pipelines.dirac_pipeline,
            &bufs.dirac_ddag_bg,
            bufs.wg_dirac,
        );

        GpuF64::encode_pass(
            enc,
            &dyn_pipelines.dot_pipeline,
            &bufs.dot_pap_bg,
            bufs.wg_dot,
        );
        encode_reduce_chain(enc, &ms_pipelines.base.reduce_pipeline, &bufs.reduce_to_pap);
        GpuF64::encode_pass(
            enc,
            &dyn_pipelines.dot_pipeline,
            &bufs.dot_pp_bg,
            bufs.wg_dot,
        );
        encode_reduce_chain(enc, &ms_pipelines.base.reduce_pipeline, &bufs.reduce_to_pp);
        GpuF64::encode_pass(
            enc,
            &ms_pipelines.shifted_alpha_pipeline,
            &bufs.compute_alpha_bg,
            1,
        );

        GpuF64::encode_pass(enc, &ms_pipelines.zeta_pipeline, &bufs.zeta_bg, 1);

        for ms_bg in ms_x_bgs.iter().take(bufs.n_shifts) {
            GpuF64::encode_pass(enc, &ms_pipelines.ms_x_pipeline, ms_bg, bufs.wg_vec);
        }

        GpuF64::encode_pass(
            enc,
            &ms_pipelines.shifted_xr_pipeline,
            &bufs.update_xr_bg,
            bufs.wg_vec,
        );

        GpuF64::encode_pass(
            enc,
            &dyn_pipelines.dot_pipeline,
            &bufs.dot_rr_bg,
            bufs.wg_dot,
        );
        encode_reduce_chain(
            enc,
            &ms_pipelines.base.reduce_pipeline,
            &bufs.reduce_to_rz_new,
        );

        GpuF64::encode_pass(
            enc,
            &ms_pipelines.base.compute_beta_pipeline,
            &bufs.compute_beta_bg,
            1,
        );

        GpuF64::encode_pass(
            enc,
            &ms_pipelines.base.update_p_pipeline,
            &bufs.update_p_bg,
            bufs.wg_vec,
        );

        for ms_p_bg in bufs.ms_p_bgs.iter().take(bufs.n_shifts) {
            GpuF64::encode_pass(enc, &ms_pipelines.ms_p_pipeline, ms_p_bg, bufs.wg_vec);
        }

        enc.copy_buffer_to_buffer(&bufs.alpha_buf, 0, &bufs.alpha_prev_buf, 0, 8);
        enc.copy_buffer_to_buffer(&bufs.beta_buf, 0, &bufs.beta_prev_buf, 0, 8);
    }
}

/// True multi-shift CG: solve (D†D + σ_s) x_s = b for all shifts simultaneously.
///
/// Uses a single Krylov subspace: only 1 D†D application per iteration instead
/// of N_shifts. Convergence via exponential back-off on the base residual.
///
/// Returns total CG iterations (shared across all shifts).
#[must_use]
#[inline(never)]
pub fn gpu_true_multi_shift_cg_solve(
    gpu: &GpuF64,
    dyn_pipelines: &GpuDynHmcPipelines,
    ms_pipelines: &TrueMultiShiftPipelines,
    state: &GpuDynHmcState,
    bufs: &TrueMultiShiftBuffers,
    x_bufs: &[wgpu::Buffer],
    b_buf: &wgpu::Buffer,
    shifts: &[f64],
    tol: f64,
    max_iter: usize,
    check_interval: usize,
) -> usize {
    let n_flat = bufs.n_flat;
    let n_shifts = shifts.len();
    assert_eq!(n_shifts, bufs.n_shifts);

    // Use σ_min as base shift; effective shifts δ_s = σ_s - σ_min
    let sigma_min = shifts.iter().copied().fold(f64::INFINITY, f64::min);
    // Exact match: `sigma_min` is one of the discrete shift values in `shifts`.
    #[allow(clippy::float_cmp)]
    let i_min = shifts.iter().position(|&s| s == sigma_min).unwrap_or(0);
    let effective_shifts: Vec<f64> = shifts.iter().map(|&s| s - sigma_min).collect();

    gpu.upload_f64(&bufs.sigma_buf, &effective_shifts);
    gpu.upload_f64(&bufs.sigma_min_buf, &[sigma_min]);

    for xb in x_bufs.iter().take(n_shifts) {
        gpu.zero_buffer(xb, (n_flat * 8) as u64);
    }
    gpu.zero_buffer(&state.x_buf, (n_flat * 8) as u64);

    // Initialize: r = b, p_base = b, p_s = b for all s
    {
        let mut enc = gpu.begin_encoder("ms_init");
        enc.copy_buffer_to_buffer(b_buf, 0, &state.r_buf, 0, (n_flat * 8) as u64);
        enc.copy_buffer_to_buffer(b_buf, 0, &state.p_buf, 0, (n_flat * 8) as u64);
        for s in 0..n_shifts {
            enc.copy_buffer_to_buffer(b_buf, 0, &bufs.p_shift_bufs[s], 0, (n_flat * 8) as u64);
        }

        // ⟨b|b⟩ → rz
        GpuF64::encode_pass(
            &mut enc,
            &dyn_pipelines.dot_pipeline,
            &bufs.dot_rr_bg,
            bufs.wg_dot,
        );
        encode_reduce_chain(
            &mut enc,
            &ms_pipelines.base.reduce_pipeline,
            &bufs.reduce_to_rz,
        );
        enc.copy_buffer_to_buffer(&bufs.rz_buf, 0, &bufs.convergence_staging, 0, 8);
        gpu.submit_encoder(enc);
    }

    let b_norm_sq = match gpu.read_staging_f64(&bufs.convergence_staging) {
        Ok(v) => v.first().copied().unwrap_or(0.0),
        Err(_) => return 0,
    };
    if b_norm_sq < 1e-30 {
        return 0;
    }
    let tol_sq = tol * tol * b_norm_sq;

    // Initialize ζ = 1, α_prev = 1, β_prev = 0
    let ones = vec![1.0_f64; n_shifts];
    gpu.upload_f64(&bufs.zeta_curr_buf, &ones);
    gpu.upload_f64(&bufs.zeta_prev_buf, &ones);
    gpu.upload_f64(&bufs.alpha_prev_buf, &[1.0_f64]);
    gpu.upload_f64(&bufs.beta_prev_buf, &[0.0_f64]);

    // Pre-create per-shift x-update bind groups (depend on caller's x_bufs)
    let ms_x_bgs: Vec<_> = (0..n_shifts)
        .map(|s| {
            let mut params = [0u32; 4];
            params[0] = n_flat as u32;
            params[1] = s as u32;
            let pbuf =
                gpu.create_uniform_buffer(bytemuck::cast_slice(&params), &format!("ms_xu_{s}"));
            gpu.create_bind_group(
                &ms_pipelines.ms_x_pipeline,
                &[&pbuf, &x_bufs[s], &bufs.p_shift_bufs[s], &bufs.alpha_s_buf],
            )
        })
        .collect();

    let mut current_interval = check_interval.max(1);
    let mut total_iters = 0;

    loop {
        let batch = current_interval.min(max_iter - total_iters);
        if batch == 0 {
            break;
        }

        let mut enc = gpu.begin_encoder("ms_batch");
        encode_ms_cg_batch(
            &mut enc,
            dyn_pipelines,
            ms_pipelines,
            bufs,
            &ms_x_bgs,
            batch,
        );
        enc.copy_buffer_to_buffer(&bufs.rz_new_buf, 0, &bufs.convergence_staging, 0, 8);
        gpu.submit_encoder(enc);
        total_iters += batch;

        let rz_new = match gpu.read_staging_f64(&bufs.convergence_staging) {
            Ok(v) => v.first().copied().unwrap_or(f64::MAX),
            Err(_) => break,
        };
        if std::hint::black_box(rz_new) < tol_sq || total_iters >= max_iter {
            break;
        }

        current_interval = (current_interval * 2).min(CG_BACKOFF_CAP);
    }

    // Base solution x_buf corresponds to σ_min → copy to x_bufs[i_min]
    {
        let mut enc = gpu.begin_encoder("ms_base_copy");
        enc.copy_buffer_to_buffer(&state.x_buf, 0, &x_bufs[i_min], 0, (n_flat * 8) as u64);
        gpu.submit_encoder(enc);
    }

    total_iters
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    fn make_gpu() -> GpuF64 {
        let rt = tokio::runtime::Runtime::new().expect("tokio");
        rt.block_on(GpuF64::new()).expect("GPU required for test")
    }

    #[test]
    fn zeta_recurrence_first_iteration() {
        let gpu = make_gpu();
        let n_shifts = 3usize;
        let sigma = [0.1, 0.5, 1.0];

        let pl = gpu.create_pipeline_f64(WGSL_MS_ZETA, "test_zeta");

        let params = make_u32x4_params(n_shifts as u32);
        let params_buf = gpu.create_uniform_buffer(&params, "tz_params");
        let sigma_buf = gpu.create_f64_output_buffer(n_shifts, "tz_sigma");
        let zeta_curr_buf = gpu.create_f64_output_buffer(n_shifts, "tz_zc");
        let zeta_prev_buf = gpu.create_f64_output_buffer(n_shifts, "tz_zp");
        let alpha_s_buf = gpu.create_f64_output_buffer(n_shifts, "tz_as");
        let beta_ratio_buf = gpu.create_f64_output_buffer(n_shifts, "tz_br");
        let alpha_buf = gpu.create_f64_output_buffer(1, "tz_alpha");
        let beta_prev_buf = gpu.create_f64_output_buffer(1, "tz_bprev");
        let alpha_prev_buf = gpu.create_f64_output_buffer(1, "tz_aprev");

        gpu.upload_f64(&sigma_buf, &sigma);
        gpu.upload_f64(&zeta_curr_buf, &[1.0, 1.0, 1.0]);
        gpu.upload_f64(&zeta_prev_buf, &[1.0, 1.0, 1.0]);
        gpu.upload_f64(&alpha_buf, &[0.3]); // α₀ for this iteration
        gpu.upload_f64(&beta_prev_buf, &[0.0]); // β_{-1} = 0
        gpu.upload_f64(&alpha_prev_buf, &[1.0]); // α_{-1} = 1

        let bg = gpu.create_bind_group(
            &pl,
            &[
                &params_buf,
                &sigma_buf,
                &zeta_curr_buf,
                &zeta_prev_buf,
                &alpha_s_buf,
                &beta_ratio_buf,
                &alpha_buf,
                &beta_prev_buf,
                &alpha_prev_buf,
            ],
        );

        let mut enc = gpu.begin_encoder("test_zeta");
        GpuF64::encode_pass(&mut enc, &pl, &bg, 1);
        gpu.submit_encoder(enc);

        let zeta = gpu.read_back_f64(&zeta_curr_buf, n_shifts).unwrap();
        let alpha_s = gpu.read_back_f64(&alpha_s_buf, n_shifts).unwrap();

        // For first iteration (β_{-1}=0, α_{-1}=1, ζ=ζ_prev=1):
        //   ζ^1 = 1·1·1 / (0·1·(1-1) + 1·1·(1 + σ·0.3))
        //       = 1 / (1 + 0.3·σ)
        for (s, &sig) in sigma.iter().enumerate() {
            let expected_z = 1.0 / (1.0 + sig * 0.3);
            let expected_a = 0.3 * expected_z; // α_s = α₀ · ζ_new / ζ_old = 0.3 · ζ_new / 1
            assert!(
                (zeta[s] - expected_z).abs() < 1e-10,
                "shift {s}: ζ expected {expected_z}, got {}",
                zeta[s]
            );
            assert!(
                (alpha_s[s] - expected_a).abs() < 1e-10,
                "shift {s}: α_s expected {expected_a}, got {}",
                alpha_s[s]
            );
        }
        eprintln!("  zeta recurrence passed: ζ={zeta:?}");
    }

    #[test]
    fn ms_x_update_kernel() {
        let gpu = make_gpu();
        let n = 64usize;
        let shift_idx = 1u32;
        let n_shifts = 3usize;

        let pl = gpu.create_pipeline_f64(WGSL_MS_X_UPDATE, "test_mx");

        let mut params = [0u32; 4];
        params[0] = n as u32;
        params[1] = shift_idx;
        let pbuf = gpu.create_uniform_buffer(bytemuck::cast_slice(&params), "tmx_p");
        let x_buf = gpu.create_f64_output_buffer(n, "tmx_x");
        let p_buf = gpu.create_f64_output_buffer(n, "tmx_p2");
        let alpha_s_buf = gpu.create_f64_output_buffer(n_shifts, "tmx_as");

        let x_init: Vec<f64> = (0..n).map(|i| i as f64).collect();
        let p_init: Vec<f64> = (0..n).map(|_| 2.0).collect();
        gpu.upload_f64(&x_buf, &x_init);
        gpu.upload_f64(&p_buf, &p_init);
        gpu.upload_f64(&alpha_s_buf, &[0.0, 0.5, 0.0]); // α for shift 1 = 0.5

        let bg = gpu.create_bind_group(&pl, &[&pbuf, &x_buf, &p_buf, &alpha_s_buf]);
        let wg = (n as u32).div_ceil(64);
        let mut enc = gpu.begin_encoder("test_mx");
        GpuF64::encode_pass(&mut enc, &pl, &bg, wg);
        gpu.submit_encoder(enc);

        let x_out = gpu.read_back_f64(&x_buf, n).unwrap();
        for (i, &val) in x_out.iter().enumerate() {
            let expected = i as f64 + 0.5 * 2.0; // x + α_1 · p
            assert!(
                (val - expected).abs() < 1e-10,
                "x[{i}] = {val}, expected {expected}"
            );
        }
        eprintln!("  ms_x_update passed");
    }

    #[test]
    fn ms_p_update_kernel() {
        let gpu = make_gpu();
        let n = 64usize;
        let shift_idx = 0u32;
        let n_shifts = 2usize;

        let pl = gpu.create_pipeline_f64(WGSL_MS_P_UPDATE, "test_mp");

        let mut params = [0u32; 4];
        params[0] = n as u32;
        params[1] = shift_idx;
        let pbuf = gpu.create_uniform_buffer(bytemuck::cast_slice(&params), "tmp_p");
        let p_buf = gpu.create_f64_output_buffer(n, "tmp_p2");
        let r_buf = gpu.create_f64_output_buffer(n, "tmp_r");
        let zeta_buf = gpu.create_f64_output_buffer(n_shifts, "tmp_z");
        let beta_ratio_buf = gpu.create_f64_output_buffer(n_shifts, "tmp_br");
        let beta_base_buf = gpu.create_f64_output_buffer(1, "tmp_bb");

        let p_init: Vec<f64> = (0..n).map(|_| 3.0).collect();
        let r_init: Vec<f64> = (0..n).map(|_| 1.0).collect();
        gpu.upload_f64(&p_buf, &p_init);
        gpu.upload_f64(&r_buf, &r_init);
        gpu.upload_f64(&zeta_buf, &[0.8, 0.6]); // ζ₀ = 0.8
        gpu.upload_f64(&beta_ratio_buf, &[0.9, 0.7]); // ratio₀ = 0.9
        gpu.upload_f64(&beta_base_buf, &[0.4]); // β_base = 0.4

        let bg = gpu.create_bind_group(
            &pl,
            &[
                &pbuf,
                &p_buf,
                &r_buf,
                &zeta_buf,
                &beta_ratio_buf,
                &beta_base_buf,
            ],
        );
        let wg = (n as u32).div_ceil(64);
        let mut enc = gpu.begin_encoder("test_mp");
        GpuF64::encode_pass(&mut enc, &pl, &bg, wg);
        gpu.submit_encoder(enc);

        let p_out = gpu.read_back_f64(&p_buf, n).unwrap();
        // p = ζ · r + (ratio² · β_base) · p_old
        //   = 0.8 · 1.0 + (0.81 · 0.4) · 3.0
        //   = 0.8 + 0.972
        //   = 1.772
        let beta_s = 0.9 * 0.9 * 0.4;
        let expected = 0.8 * 1.0 + beta_s * 3.0;
        for (i, &val) in p_out.iter().enumerate() {
            assert!(
                (val - expected).abs() < 1e-10,
                "p[{i}] = {val}, expected {expected}"
            );
        }
        eprintln!("  ms_p_update passed: p[0] = {}", p_out[0]);
    }
}
