#!/usr/bin/env bash
# ecoBin harvest: build hotSpring musl-static binaries and submit to plasmidBin.
#
# Builds for x86_64-unknown-linux-musl and (optionally) aarch64-unknown-linux-musl,
# then harvests into ecoPrimals/infra/plasmidBin/ per ECOBIN_ARCHITECTURE_STANDARD v3.0.
#
# Usage:
#   ./scripts/harvest-ecobin.sh                     # x86_64 only
#   ./scripts/harvest-ecobin.sh --cross-aarch64     # both architectures
#
# Prerequisites:
#   - musl-tools installed (apt install musl-tools)
#   - For aarch64: aarch64-linux-musl-gcc cross-compiler
#   - .cargo/config.toml already configures musl targets
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLASMIDB="${ROOT}/../../infra/plasmidBin"

if [ ! -d "$PLASMIDB" ]; then
    echo "ERROR: plasmidBin not found at $PLASMIDB"
    echo "  Expected: ecoPrimals/infra/plasmidBin/"
    exit 1
fi

CROSS_AARCH64=false
for arg in "$@"; do
    case "$arg" in
        --cross-aarch64) CROSS_AARCH64=true ;;
    esac
done

echo "=== hotSpring ecoBin Harvest ==="
echo "  Source: $ROOT/barracuda"
echo "  Target: $PLASMIDB"
echo ""

# ── Build x86_64 musl-static ──
echo "  Building x86_64-unknown-linux-musl (release, stripped, LTO)..."
cd "$ROOT/barracuda"
cargo build --release --target x86_64-unknown-linux-musl --bin hotspring_primal

BINARY_X86="target/x86_64-unknown-linux-musl/release/hotspring_primal"
if [ ! -f "$BINARY_X86" ]; then
    echo "ERROR: binary not found at $BINARY_X86"
    exit 1
fi

echo "  Verifying static linkage..."
file "$BINARY_X86" | grep -q "statically linked" || {
    echo "WARNING: binary may not be statically linked:"
    file "$BINARY_X86"
}

BINARY_SIZE=$(stat -c%s "$BINARY_X86" 2>/dev/null || stat -f%z "$BINARY_X86")
echo "  Binary: $BINARY_X86 ($(( BINARY_SIZE / 1024 / 1024 )) MB)"

# ── Harvest to plasmidBin ──
echo ""
echo "  Harvesting to plasmidBin..."
if [ -x "$PLASMIDB/harvest.sh" ]; then
    "$PLASMIDB/harvest.sh" --primal hotspring --source "$(dirname "$BINARY_X86")"
else
    mkdir -p "$PLASMIDB/hotspring/x86_64"
    cp "$BINARY_X86" "$PLASMIDB/hotspring/x86_64/hotspring_primal"
    echo "  Copied to $PLASMIDB/hotspring/x86_64/hotspring_primal"
fi

# ── b3sum checksum ──
if command -v b3sum &>/dev/null; then
    B3=$(b3sum "$BINARY_X86" | cut -d' ' -f1)
    echo "  b3sum (x86_64): $B3"
fi

# ── Cross-compile aarch64 ──
if $CROSS_AARCH64; then
    echo ""
    echo "  Building aarch64-unknown-linux-musl..."
    cargo build --release --target aarch64-unknown-linux-musl --bin hotspring_primal

    BINARY_ARM="target/aarch64-unknown-linux-musl/release/hotspring_primal"
    if [ -f "$BINARY_ARM" ]; then
        if [ -x "$PLASMIDB/harvest.sh" ]; then
            "$PLASMIDB/harvest.sh" --primal hotspring --arch aarch64 --source "$(dirname "$BINARY_ARM")"
        else
            mkdir -p "$PLASMIDB/hotspring/aarch64"
            cp "$BINARY_ARM" "$PLASMIDB/hotspring/aarch64/hotspring_primal"
            echo "  Copied to $PLASMIDB/hotspring/aarch64/hotspring_primal"
        fi
        if command -v b3sum &>/dev/null; then
            B3_ARM=$(b3sum "$BINARY_ARM" | cut -d' ' -f1)
            echo "  b3sum (aarch64): $B3_ARM"
        fi
    fi
fi

# ── Write metadata.toml ──
VERSION=$(grep '^version' "$ROOT/barracuda/Cargo.toml" | head -1 | cut -d'"' -f2)
cat > "$PLASMIDB/hotspring/metadata.toml" <<TOML
# hotSpring ecoBin metadata — auto-generated by harvest-ecobin.sh
[primal]
name = "hotspring"
version = "$VERSION"
license = "AGPL-3.0-or-later"
binary = "hotspring_primal"
description = "Computational physics validation: nuclear EOS, lattice QCD, GPU MD"

[ecobin]
standard = "v3.0"
static_musl = true
cross_compile = $CROSS_AARCH64
socket_convention = "hotspring-physics.sock"
health_method = "health.liveness"
capabilities_method = "capabilities.list"

[harvest]
date = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
source = "ecoPrimals/springs/hotSpring"
TOML

echo ""
echo "=== Harvest complete ==="
echo "  Metadata: $PLASMIDB/hotspring/metadata.toml"
echo "  Version: $VERSION"
