#!/usr/bin/env python
"""
Generate Sarkas YAML input files for the Yukawa DSF database reproduction study.

Matches the exact parameters from the Dense Plasma Properties Database:
  - N = 10,000 particles
  - dt = 0.01 (reduced, omega_p^{-1})
  - 80,000 timesteps (production)
  - PPPM method for long-range forces
  - kappa = 0, 1, 2, 3 with specific Gamma values

Reference:
  Choi, Dharuman, Murillo - "High-Frequency Response of Classical Strongly Coupled Plasmas"
  Dense Plasma Properties Database - Yukawa_Dynamic_Structure_Factors/

Physical setup follows the OCP MKS example from Sarkas:
  Species: H (proton), Z = 1
  n = 1.62e30 /m^3  (gives a_ws ~ 5.28e-11 m)
  Mass = 1.673e-27 kg

The coupling parameter Gamma = e^2 / (4*pi*eps0 * a_ws * kB * T)
is controlled by adjusting T for each case.

The screening parameter kappa = a_ws / lambda_D
is set directly in the Yukawa potential block.
"""

import os
import sys
import numpy as np
from pathlib import Path

# ============================================================
# Physical constants (CODATA 2018, matching Sarkas internals)
# ============================================================
e = 1.602176634e-19       # C, elementary charge
eps0 = 8.8541878128e-12   # F/m, vacuum permittivity
kB = 1.380649e-23         # J/K, Boltzmann constant
m_p = 1.67262192369e-27   # kg, proton mass
fourpie0 = 4.0 * np.pi * eps0

# ============================================================
# Fixed simulation parameters (matching OCP MKS example)
# ============================================================
Z = 1.0
n = 1.62e30               # /m^3, number density
mass = m_p                 # kg, proton mass
N = 10000                  # particle count (matching database)

# ============================================================
# Derived quantities
# ============================================================
a_ws = (3.0 / (4.0 * np.pi * n)) ** (1.0 / 3.0)   # Wigner-Seitz radius
omega_p = np.sqrt(n * (Z * e)**2 / (eps0 * mass))   # plasma frequency
Q = Z * e                                            # particle charge

print("=" * 70)
print("Yukawa DSF Study - Parameter Generation")
print("=" * 70)
print(f"Species: H (proton), Z = {Z}")
print(f"Number density: {n:.4e} /m^3")
print(f"Wigner-Seitz radius: {a_ws:.6e} m")
print(f"Plasma frequency: {omega_p:.6e} rad/s")
print(f"Particles: {N}")
print()

# ============================================================
# Study matrix - from the DSF database README
# ============================================================
study_cases = [
    # (kappa, Gamma)
    (0, 10), (0, 50), (0, 150),       # OCP cases
    (1, 14), (1, 72), (1, 217),       # moderate screening
    (2, 31), (2, 158), (2, 476),      # strong screening
    (3, 100), (3, 503), (3, 1510),    # very strong screening
]

# ============================================================
# Reduced time step -> physical
# ============================================================
dt_reduced = 0.01                      # matching database
dt_phys = dt_reduced / omega_p         # seconds

# Equilibration: 5000 steps (standard in Sarkas examples)
# Production: 80,000 steps (matching database exactly)
eq_steps = 5000
prod_steps = 80000
eq_dump = 10
prod_dump = 5   # dump every 5 steps; gives 16000 snapshots, adequate for DSF resolution
                # (database has 764 freq points over 0<w<3; Nyquist at w=pi/(dt*dump)=62.8)

# ============================================================
# PPPM parameters (matching OCP MKS example)
# ============================================================
# rc ~ 6.25 a_ws (standard for N=10000)
rc = 6.25 * a_ws
pppm_mesh = [64, 64, 64]
pppm_aliases = [3, 3, 3]
pppm_cao = 6
# alpha_ewald ~ 0.56 / a_ws (standard Sarkas choice for this setup)
pppm_alpha_ewald = 0.56 / a_ws  # will be refined by pppm_estimate

# ============================================================
# DSF observable parameters (matching database)
# max_k_harmonics controls how many ka values are computed
# The database has 166 ka values with dka = 0.181
# This means max_k_harmonics ~ 30 (Sarkas generates multiple harmonics per value)
# ============================================================
max_k_harmonics = 30

# ============================================================
# Generate YAML files
# ============================================================
YAML_TEMPLATE_PPPM = """\
# Yukawa DSF Study: kappa={kappa}, Gamma={gamma}
# Reproducing Dense Plasma Properties Database reference data
# Choi, Dharuman, Murillo - Phys. Rev. E
# Generated by hotSpring/control/sarkas/simulations/dsf-study/scripts/generate_inputs.py
#
# Reduced parameters:
#   dt_reduced = {dt_reduced}
#   Gamma_target = {gamma}
#   kappa_target = {kappa}
#   a_ws = {a_ws:.6e} m
#   omega_p = {omega_p:.6e} rad/s
#   T = {temperature:.4f} K ({temperature_eV:.6f} eV)
# Method: PPPM (Coulomb, long-range, requires Ewald summation)

Particles:
    - Species:
        name: H
        number_density: {n:.4e}       # /m^3
        mass: {mass:.6e}              # kg, proton mass
        num: {N}                      # total number of particles
        Z: {Z}                        # degree of ionization
        temperature: {temperature:.6e}

Potential:
    type: Coulomb
    method: pppm
    rc: {rc:.6e}                      # cut-off radius, meter (~6.25 a_ws)
    pppm_mesh: [{mesh}]
    pppm_aliases: [{aliases}]
    pppm_cao: {cao}
    pppm_alpha_ewald: {alpha:.6e}

Integrator:
    type: Verlet
    dt: {dt:.6e}                      # sec (dt_reduced = {dt_reduced})
    equilibration_steps: {eq_steps}
    production_steps: {prod_steps}
    eq_dump_step: {eq_dump}
    prod_dump_step: {prod_dump}

Thermostat:
    type: Berendsen
    relaxation_timestep: 0
    berendsen_tau: 5.0

Parameters:
    units: mks
    load_method: random_no_reject
    rdf_nbins: 500
    boundary_conditions: periodic

IO:
    verbose: True
    job_dir: dsf_k{kappa}_G{gamma}

Observables:
  - RadialDistributionFunction:
      no_bins: 500

  - Thermodynamics:
      phase: production

  - DynamicStructureFactor:
      max_k_harmonics: {max_k_harmonics}

  - StaticStructureFactor:
      max_k_harmonics: {max_k_harmonics}

  - VelocityAutoCorrelationFunction:
      phase: production
"""

YAML_TEMPLATE_PP = """\
# Yukawa DSF Study: kappa={kappa}, Gamma={gamma}
# Reproducing Dense Plasma Properties Database reference data
# Choi, Dharuman, Murillo - Phys. Rev. E
# Generated by hotSpring/control/sarkas/simulations/dsf-study/scripts/generate_inputs.py
#
# Reduced parameters:
#   dt_reduced = {dt_reduced}
#   Gamma_target = {gamma}
#   kappa_target = {kappa}
#   a_ws = {a_ws:.6e} m
#   omega_p = {omega_p:.6e} rad/s
#   T = {temperature:.4f} K ({temperature_eV:.6f} eV)
# Method: PP (Yukawa, short-range, direct pair sum with cutoff)
# Force error at rc: exp(-kappa*rc/a_ws) = {force_decay:.2e}

Particles:
    - Species:
        name: H
        number_density: {n:.4e}       # /m^3
        mass: {mass:.6e}              # kg, proton mass
        num: {N}                      # total number of particles
        Z: {Z}                        # degree of ionization
        temperature: {temperature:.6e}

Potential:
    type: Yukawa
    method: PP
    rc: {rc_pp:.6e}                   # cut-off radius, meter (~{rc_aws:.1f} a_ws)
    kappa: {kappa:.1f}

Integrator:
    type: Verlet
    dt: {dt:.6e}                      # sec (dt_reduced = {dt_reduced})
    equilibration_steps: {eq_steps}
    production_steps: {prod_steps}
    eq_dump_step: {eq_dump}
    prod_dump_step: {prod_dump}

Thermostat:
    type: Berendsen
    relaxation_timestep: 0
    berendsen_tau: 5.0

Parameters:
    units: mks
    load_method: random_no_reject
    rdf_nbins: 500
    boundary_conditions: periodic

IO:
    verbose: True
    job_dir: dsf_k{kappa}_G{gamma}

Observables:
  - RadialDistributionFunction:
      no_bins: 500

  - Thermodynamics:
      phase: production

  - DynamicStructureFactor:
      max_k_harmonics: {max_k_harmonics}

  - StaticStructureFactor:
      max_k_harmonics: {max_k_harmonics}

  - VelocityAutoCorrelationFunction:
      phase: production
"""

output_dir = Path(__file__).resolve().parent.parent / "input_files"
output_dir.mkdir(exist_ok=True)

print(f"{'Case':<15} {'Method':<6} {'T (K)':>12} {'T (eV)':>10} {'dt (s)':>14}")
print("-" * 70)

generated_files = []

for kappa, gamma in study_cases:
    # Calculate temperature for desired Gamma
    # Gamma = Q^2 / (fourpie0 * a_ws * kB * T)
    # => T = Q^2 / (fourpie0 * a_ws * kB * Gamma)
    T = Q**2 / (fourpie0 * a_ws * kB * gamma)
    T_eV = T * kB / e  # convert to eV

    # Format PPPM parameters
    mesh_str = ", ".join(str(m) for m in pppm_mesh)
    aliases_str = ", ".join(str(a) for a in pppm_aliases)

    if kappa == 0:
        # OCP (Coulomb) - needs PPPM for long-range 1/r potential
        method = "PPPM"
        yaml_content = YAML_TEMPLATE_PPPM.format(
            kappa=kappa, gamma=gamma, dt_reduced=dt_reduced,
            a_ws=a_ws, omega_p=omega_p, temperature=T, temperature_eV=T_eV,
            n=n, mass=mass, N=N, Z=Z,
            rc=rc, mesh=mesh_str, aliases=aliases_str,
            cao=pppm_cao, alpha=pppm_alpha_ewald,
            dt=dt_phys, eq_steps=eq_steps, prod_steps=prod_steps,
            eq_dump=eq_dump, prod_dump=prod_dump,
            max_k_harmonics=max_k_harmonics,
        )
    else:
        # Yukawa - PP with cutoff; potential decays as exp(-kappa*r/a_ws)
        # Use larger cutoff for lower kappa to ensure accuracy
        rc_multiplier = {1: 8.0, 2: 6.5, 3: 6.0}  # a_ws multiples
        rc_aws = rc_multiplier.get(kappa, 6.25)
        rc_pp = rc_aws * a_ws
        force_decay = np.exp(-kappa * rc_aws)
        method = "PP"
        yaml_content = YAML_TEMPLATE_PP.format(
            kappa=kappa, gamma=gamma, dt_reduced=dt_reduced,
            a_ws=a_ws, omega_p=omega_p, temperature=T, temperature_eV=T_eV,
            n=n, mass=mass, N=N, Z=Z,
            rc_pp=rc_pp, rc_aws=rc_aws, force_decay=force_decay,
            dt=dt_phys, eq_steps=eq_steps, prod_steps=prod_steps,
            eq_dump=eq_dump, prod_dump=prod_dump,
            max_k_harmonics=max_k_harmonics,
        )

    filename = f"dsf_k{kappa}_G{gamma}_mks.yaml"
    filepath = output_dir / filename
    filepath.write_text(yaml_content)
    generated_files.append(filepath)

    print(f"k={kappa} G={gamma:<5} {method:<5} {T:>12.2f} {T_eV:>10.6f} {dt_phys:>14.6e}")

print(f"\n{len(generated_files)} YAML files written to {output_dir}/")
print("\nGenerated files:")
for f in generated_files:
    print(f"  {f.name}")

# Also write a manifest for the runner
manifest = output_dir / "MANIFEST.txt"
manifest.write_text("\n".join(f.name for f in generated_files) + "\n")
print(f"\nManifest: {manifest}")
