#!/usr/bin/env python3
"""Generate initial PDB structures for free sugar epimer FEL calculations.

Uses RDKit to generate 3D conformers, then maps atom names to CHARMM36 convention.
Each sugar is output as a single-residue PDB ready for gmx pdb2gmx.
"""
from rdkit import Chem
from rdkit.Chem import AllChem, rdMolTransforms
import os

SUGARS = {
    "lyxose": {
        "smiles": "O[C@@H]1CO[C@H](O)[C@H](O)[C@H]1O",
        "resname": "BLYXP",
        "desc": "beta-D-Lyxopyranose (C2 epimer of xylose)",
        "heavy_map": {
            # Ring: C1,C2,C3,C4,C5,O5 + exocyclic O1,O2,O3,O4
            # SMILES atom order after AddHs may vary - we identify by connectivity
        },
        "natoms_heavy": 10,
    },
    "glucose": {
        "smiles": "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O",
        "resname": "BGLC",
        "desc": "beta-D-Glucopyranose (hexose, xylose + CH2OH at C5)",
        "natoms_heavy": 12,
    },
    "mannose": {
        "smiles": "OC[C@H]1OC(O)[C@@H](O)[C@@H](O)[C@@H]1O",
        "resname": "BMAN",
        "desc": "beta-D-Mannopyranose (C2 epimer of glucose)",
        "natoms_heavy": 12,
    },
    "galactose": {
        "smiles": "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@H]1O",
        "resname": "BGAL",
        "desc": "beta-D-Galactopyranose (C4 epimer of glucose)",
        "natoms_heavy": 12,
    },
}

CHARMM_PENTOSE_ORDER = [
    ("O1", "O"), ("C1", "C"), ("O5", "O"), ("C5", "C"), ("C4", "C"),
    ("O4", "O"), ("C3", "C"), ("O3", "O"), ("C2", "C"), ("O2", "O"),
]
CHARMM_PENTOSE_H = ["HO1", "H1", "H51", "H52", "H4", "HO4", "H3", "HO3", "H2", "HO2"]

CHARMM_HEXOSE_ORDER = [
    ("O1", "O"), ("C1", "C"), ("O5", "O"), ("C5", "C"), ("C4", "C"),
    ("O4", "O"), ("C3", "C"), ("O3", "O"), ("C2", "C"), ("O2", "O"),
    ("C6", "C"), ("O6", "O"),
]
CHARMM_HEXOSE_H = ["HO1", "H1", "H5", "H4", "HO4", "H3", "HO3", "H2", "HO2", "H61", "H62", "HO6"]


def generate_pdb(name, info, outdir):
    """Generate a PDB file for a sugar using RDKit."""
    mol = Chem.MolFromSmiles(info["smiles"])
    mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    AllChem.EmbedMolecule(mol, params)
    AllChem.MMFFOptimizeMolecule(mol, maxIters=500)

    resname = info["resname"]
    is_hexose = info["natoms_heavy"] == 12

    outpath = os.path.join(outdir, f"{name}_charmm.pdb")
    with open(outpath, "w") as f:
        f.write(f"REMARK   {info['desc']}\n")
        f.write(f"REMARK   Generated by generate_sugar_pdbs.py for CHARMM36 {resname}\n")

        conf = mol.GetConformer()
        atom_idx = 1
        # Write heavy atoms first, then hydrogens (CHARMM convention)
        heavy_atoms = []
        h_atoms = []
        for i in range(mol.GetNumAtoms()):
            atom = mol.GetAtomWithIdx(i)
            pos = conf.GetAtomPosition(i)
            if atom.GetAtomicNum() == 1:
                h_atoms.append((i, pos))
            else:
                heavy_atoms.append((i, atom.GetSymbol(), pos))

        # Assign CHARMM names based on element and ring membership
        ring_info = mol.GetRingInfo()
        ring_atoms = set()
        for ring in ring_info.AtomRings():
            if len(ring) == 6:
                ring_atoms = set(ring)
                break

        # Identify ring carbons and oxygens
        ring_carbons = []
        ring_oxygen = None
        for idx in ring_atoms:
            atom = mol.GetAtomWithIdx(idx)
            if atom.GetSymbol() == "O":
                ring_oxygen = idx
            elif atom.GetSymbol() == "C":
                ring_carbons.append(idx)

        # For pyranose: O5 is the ring oxygen, C1 is adjacent to O5 and has an -OH
        # Walk the ring from O5 to assign C1,C2,C3,C4,C5
        if ring_oxygen is not None and len(ring_carbons) == 5:
            # Find neighbors of ring oxygen that are in the ring
            o5_neighbors_in_ring = [n.GetIdx() for n in mol.GetAtomWithIdx(ring_oxygen).GetNeighbors() if n.GetIdx() in ring_atoms]

            # C1 is the one with an exocyclic -OH; C5 is the other
            c1_idx = None
            c5_idx = None
            for n in o5_neighbors_in_ring:
                neighbors = [x.GetIdx() for x in mol.GetAtomWithIdx(n).GetNeighbors()]
                exo_oxygens = [x for x in neighbors if x not in ring_atoms and mol.GetAtomWithIdx(x).GetSymbol() == "O"]
                if exo_oxygens:
                    if c1_idx is None:
                        c1_idx = n
                    else:
                        c5_idx = n
                else:
                    c5_idx = n

            if c1_idx is None or c5_idx is None:
                # Both have exocyclic O - pick based on whether one also has exocyclic C (hexose C6)
                for n in o5_neighbors_in_ring:
                    neighbors = [x.GetIdx() for x in mol.GetAtomWithIdx(n).GetNeighbors()]
                    exo_carbons = [x for x in neighbors if x not in ring_atoms and mol.GetAtomWithIdx(x).GetSymbol() == "C"]
                    if exo_carbons:
                        c5_idx = n
                    else:
                        c1_idx = n

            # Walk from C1 through ring (excluding O5) to get C2,C3,C4,C5
            ring_order = [c1_idx]
            current = c1_idx
            visited = {ring_oxygen, c1_idx}
            for _ in range(4):
                for n in mol.GetAtomWithIdx(current).GetNeighbors():
                    if n.GetIdx() in ring_atoms and n.GetIdx() not in visited:
                        ring_order.append(n.GetIdx())
                        visited.add(n.GetIdx())
                        current = n.GetIdx()
                        break

            # Now ring_order = [C1, C2, C3, C4, C5]
            name_map = {}
            cnames = ["C1", "C2", "C3", "C4", "C5"]
            for i, idx in enumerate(ring_order):
                name_map[idx] = cnames[i]
            name_map[ring_oxygen] = "O5"

            # Map exocyclic oxygens
            for i, idx in enumerate(ring_order):
                for n in mol.GetAtomWithIdx(idx).GetNeighbors():
                    nidx = n.GetIdx()
                    if nidx not in ring_atoms and n.GetSymbol() == "O" and nidx not in name_map:
                        oname = f"O{i+1}"
                        name_map[nidx] = oname
                    if nidx not in ring_atoms and n.GetSymbol() == "C" and nidx not in name_map:
                        name_map[nidx] = "C6"
                        # Find C6's oxygen
                        for nn in mol.GetAtomWithIdx(nidx).GetNeighbors():
                            if nn.GetSymbol() == "O" and nn.GetIdx() not in name_map:
                                name_map[nn.GetIdx()] = "O6"

            # Write heavy atoms
            for i, (idx, sym, pos) in enumerate(heavy_atoms):
                aname = name_map.get(idx, f"{sym}{i+1}")
                f.write(f"ATOM  {atom_idx:5d} {aname:<4s} {resname}A{1:4d}    {pos.x:8.3f}{pos.y:8.3f}{pos.z:8.3f}  1.00  0.00           {sym}\n")
                atom_idx += 1

            # Write hydrogens with CHARMM names
            h_counter = {}
            for i, (idx, pos) in enumerate(h_atoms):
                parent = mol.GetAtomWithIdx(idx).GetNeighbors()[0].GetIdx()
                parent_name = name_map.get(parent, "X")

                if parent_name.startswith("O"):
                    hname = f"H{parent_name}"
                elif parent_name.startswith("C"):
                    cnum = parent_name[1:]
                    key = parent_name
                    h_counter[key] = h_counter.get(key, 0) + 1
                    count = h_counter[key]
                    if count == 1:
                        hname = f"H{cnum}"
                    else:
                        hname = f"H{cnum}{count}"
                else:
                    hname = f"H{i+1}"

                f.write(f"ATOM  {atom_idx:5d} {hname:<4s} {resname}A{1:4d}    {pos.x:8.3f}{pos.y:8.3f}{pos.z:8.3f}  1.00  0.00           H\n")
                atom_idx += 1

        f.write("TER\nEND\n")

    print(f"  Generated: {outpath} ({atom_idx-1} atoms)")
    return outpath


if __name__ == "__main__":
    outdir = "control/gromacs_fel/cazyme_gh10"
    print("Generating sugar PDBs for CHARMM36 pdb2gmx:")
    for name, info in SUGARS.items():
        generate_pdb(name, info, outdir)
    print("Done.")
