#!/usr/bin/env python3
"""
Generate LITE Sarkas YAML inputs for transport study validation.

Reduced parameters for fast Eastgate validation:
  N = 500 (vs 2000)
  equil = 2000 steps (vs 10000)
  prod = 20000 steps (vs 100000)
  dump = 5 (2000 VACF snapshots per case)

3 key cases (one per kappa) for pipeline validation.
Full grid runs overnight via generate_transport_inputs.py.
"""

import numpy as np
from pathlib import Path

e = 1.602176634e-19
eps0 = 8.8541878128e-12
kB = 1.380649e-23
m_p = 1.67262192369e-27
fourpie0 = 4.0 * np.pi * eps0

Z = 1.0
n = 1.62e30
mass = m_p
N = 500

a_ws = (3.0 / (4.0 * np.pi * n)) ** (1.0 / 3.0)
omega_p = np.sqrt(n * (Z * e)**2 / (eps0 * mass))
Q = Z * e

dt_reduced = 0.01
dt_phys = dt_reduced / omega_p

eq_steps = 2000
prod_steps = 20000
eq_dump = 10
prod_dump = 5

lite_cases = [
    (1, 50, 8.0),
    (2, 100, 6.5),
    (3, 100, 6.0),
]

YAML_TEMPLATE = """\
# Ionic Transport Study LITE: kappa={kappa}, Gamma={gamma}
# Stanton & Murillo (2016), PRE 93 043203
# LITE: N={N}, {eq_steps} equil + {prod_steps} prod steps
# Generated by generate_transport_inputs_lite.py
#
# Reduced parameters:
#   dt_reduced = {dt_reduced}
#   Gamma_target = {gamma}
#   kappa_target = {kappa}
#   a_ws = {a_ws:.6e} m
#   omega_p = {omega_p:.6e} rad/s
#   T = {temperature:.4f} K ({temperature_eV:.6f} eV)
# Method: PP (Yukawa)
# Force error at rc: exp(-kappa*rc/a_ws) = {force_decay:.2e}

Particles:
    - Species:
        name: H
        number_density: {n:.4e}
        mass: {mass:.6e}
        num: {N}
        Z: {Z}
        temperature: {temperature:.6e}

Potential:
    type: Yukawa
    method: PP
    rc: {rc_pp:.6e}
    kappa: {kappa_reduced}

Integrator:
    type: Verlet
    dt: {dt:.6e}
    equilibration_steps: {eq_steps}
    production_steps: {prod_steps}
    eq_dump_step: {eq_dump}
    prod_dump_step: {prod_dump}

Thermostat:
    type: Berendsen
    relaxation_timestep: 0
    berendsen_tau: 5.0

Parameters:
    units: mks
    load_method: random_no_reject
    rdf_nbins: 500
    boundary_conditions: periodic

IO:
    verbose: True
    job_dir: transport_k{kappa}_G{gamma}_lite

Observables:
  - RadialDistributionFunction:
      no_bins: 500

  - Thermodynamics:
      phase: production

  - VelocityAutoCorrelationFunction:
      phase: production
"""

output_dir = Path(__file__).resolve().parent.parent / "input_files"
output_dir.mkdir(exist_ok=True)

generated = []
for kappa, gamma, rc_aws in lite_cases:
    T = Q**2 / (fourpie0 * a_ws * kB * gamma)
    T_eV = T * kB / e
    rc_pp = rc_aws * a_ws
    force_decay = np.exp(-kappa * rc_aws)

    content = YAML_TEMPLATE.format(
        kappa=kappa, gamma=gamma, dt_reduced=dt_reduced,
        a_ws=a_ws, omega_p=omega_p, temperature=T, temperature_eV=T_eV,
        n=n, mass=mass, N=N, Z=Z, kappa_reduced=kappa,
        rc_pp=rc_pp, rc_aws=rc_aws, force_decay=force_decay,
        dt=dt_phys, eq_steps=eq_steps, prod_steps=prod_steps,
        eq_dump=eq_dump, prod_dump=prod_dump,
    )
    fname = f"transport_k{kappa}_G{gamma}_lite.yaml"
    (output_dir / fname).write_text(content)
    generated.append(fname)
    print(f"  {fname}: T={T:.2f} K")

manifest = output_dir / "MANIFEST_LITE.txt"
manifest.write_text("\n".join(generated) + "\n")
print(f"\n{len(generated)} lite YAML files → {output_dir}/")
