#!/usr/bin/env python
"""
Generate Sarkas YAML input files for ionic transport coefficient reproduction.

Target paper: Stanton & Murillo (2016), PRE 93 043203
  "Ionic transport in high-energy-density matter"

Parameter grid: kappa = 1, 2, 3 with Gamma spanning weak → strong coupling.
The grid includes the original DSF study points plus intermediate values
needed for transport coefficient comparison.

Physical setup matches the DSF study (same species, density, etc.):
  Species: H (proton), Z = 1
  n = 1.62e30 /m^3
  N = 2,000 (Eastgate validation; 10,000 for paper-parity)

Key differences from DSF study:
  - prod_dump_step = 5 (fine VACF resolution: dt_dump = 0.05 omega_p^-1)
  - production_steps = 100,000 (long runs for converged Green-Kubo)
  - Observables: VACF + Thermodynamics only (no DSF needed for transport)
"""

import os
import numpy as np
from pathlib import Path

e = 1.602176634e-19
eps0 = 8.8541878128e-12
kB = 1.380649e-23
m_p = 1.67262192369e-27
fourpie0 = 4.0 * np.pi * eps0

Z = 1.0
n = 1.62e30
mass = m_p
N = 2000

a_ws = (3.0 / (4.0 * np.pi * n)) ** (1.0 / 3.0)
omega_p = np.sqrt(n * (Z * e)**2 / (eps0 * mass))
Q = Z * e

dt_reduced = 0.01
dt_phys = dt_reduced / omega_p

eq_steps = 10000
prod_steps = 100000
eq_dump = 10
prod_dump = 5  # every 5 steps → 20,000 velocity snapshots for VACF

# Transport parameter grid
# Includes original DSF points plus intermediate Gamma values
transport_cases = [
    # kappa=1: rc = 8.0 a_ws
    (1, 10,   8.0),
    (1, 14,   8.0),  # original DSF point
    (1, 30,   8.0),
    (1, 50,   8.0),
    (1, 72,   8.0),  # original DSF point
    (1, 100,  8.0),
    (1, 175,  8.0),
    # kappa=2: rc = 6.5 a_ws
    (2, 10,   6.5),
    (2, 31,   6.5),  # original DSF point
    (2, 50,   6.5),
    (2, 100,  6.5),
    (2, 158,  6.5),  # original DSF point
    (2, 300,  6.5),
    # kappa=3: rc = 6.0 a_ws
    (3, 10,   6.0),
    (3, 50,   6.0),
    (3, 100,  6.0),  # original DSF point
    (3, 300,  6.0),
    (3, 503,  6.0),  # original DSF point
]

YAML_TEMPLATE = """\
# Ionic Transport Study: kappa={kappa}, Gamma={gamma}
# Stanton & Murillo (2016), PRE 93 043203
# Generated by hotSpring transport-study/scripts/generate_transport_inputs.py
#
# Reduced parameters:
#   dt_reduced = {dt_reduced}
#   Gamma_target = {gamma}
#   kappa_target = {kappa}
#   a_ws = {a_ws:.6e} m
#   omega_p = {omega_p:.6e} rad/s
#   T = {temperature:.4f} K ({temperature_eV:.6f} eV)
# Method: PP (Yukawa, short-range, direct pair sum with cutoff)
# Force error at rc: exp(-kappa*rc/a_ws) = {force_decay:.2e}

Particles:
    - Species:
        name: H
        number_density: {n:.4e}       # /m^3
        mass: {mass:.6e}              # kg, proton mass
        num: {N}
        Z: {Z}
        temperature: {temperature:.6e}

Potential:
    type: Yukawa
    method: PP
    rc: {rc_pp:.6e}                   # cut-off radius, meter (~{rc_aws:.1f} a_ws)
    kappa: {kappa_float:.1f}

Integrator:
    type: Verlet
    dt: {dt:.6e}                      # sec (dt_reduced = {dt_reduced})
    equilibration_steps: {eq_steps}
    production_steps: {prod_steps}
    eq_dump_step: {eq_dump}
    prod_dump_step: {prod_dump}

Thermostat:
    type: Berendsen
    relaxation_timestep: 0
    berendsen_tau: 5.0

Parameters:
    units: mks
    load_method: random_no_reject
    rdf_nbins: 500
    boundary_conditions: periodic

IO:
    verbose: True
    job_dir: transport_k{kappa}_G{gamma}

Observables:
  - RadialDistributionFunction:
      no_bins: 500

  - Thermodynamics:
      phase: production

  - VelocityAutoCorrelationFunction:
      phase: production
"""

output_dir = Path(__file__).resolve().parent.parent / "input_files"
output_dir.mkdir(exist_ok=True)

print("=" * 70)
print("Transport Coefficient Study - Parameter Generation")
print("=" * 70)
print(f"Species: H (proton), Z = {Z}")
print(f"N = {N}, a_ws = {a_ws:.6e} m, omega_p = {omega_p:.6e} rad/s")
print(f"Production: {prod_steps} steps, dump every {prod_dump} steps")
print(f"VACF snapshots: {prod_steps // prod_dump}")
print()

print(f"{'Case':<15} {'T (K)':>12} {'T (eV)':>10} {'force_decay':>14}")
print("-" * 60)

generated_files = []

for kappa, gamma, rc_aws in transport_cases:
    T = Q**2 / (fourpie0 * a_ws * kB * gamma)
    T_eV = T * kB / e
    rc_pp = rc_aws * a_ws
    force_decay = np.exp(-kappa * rc_aws)

    yaml_content = YAML_TEMPLATE.format(
        kappa=kappa, gamma=gamma, dt_reduced=dt_reduced,
        a_ws=a_ws, omega_p=omega_p, temperature=T, temperature_eV=T_eV,
        n=n, mass=mass, N=N, Z=Z,
        kappa_float=float(kappa),
        rc_pp=rc_pp, rc_aws=rc_aws, force_decay=force_decay,
        dt=dt_phys, eq_steps=eq_steps, prod_steps=prod_steps,
        eq_dump=eq_dump, prod_dump=prod_dump,
    )

    filename = f"transport_k{kappa}_G{gamma}.yaml"
    filepath = output_dir / filename
    filepath.write_text(yaml_content)
    generated_files.append(filepath)

    print(f"k={kappa} G={gamma:<5} {T:>12.2f} {T_eV:>10.6f} {force_decay:>14.2e}")

print(f"\n{len(generated_files)} YAML files written to {output_dir}/")

manifest = output_dir / "MANIFEST.txt"
manifest.write_text("\n".join(f.name for f in generated_files) + "\n")
print(f"Manifest: {manifest}")
