// SPDX-License-Identifier: AGPL-3.0-only

//! QCDml 2.0 metadata generation for ILDG ensemble and config records.
//!
//! Produces XML documents conforming to the QCDml 2.0.0 schemas:
//!   - `QCDmlEnsemble2.0.0.xsd` — per-ensemble (Markov chain) metadata
//!   - `QCDmlConfig2.0.0.xsd` — per-configuration (data file) metadata
//!
//! These XML files are the "receipts" that Bazavov and the MILC collaboration
//! need to catalog, cite, and share gauge configurations through ILDG.
//!
//! # References
//!
//! - QCDml schemas: <https://hpc.desy.de/ildg/specifications/>
//! - ILDG 2.0: arXiv:2502.09253
//! - Lattice 2024 data management: arXiv:2502.08303

use super::ildg::IldgMetadata;
use super::measurement::{AlgorithmParams, ConfigEntry, EnsembleManifest, Provenance};

/// Management information for QCDml archive history events.
#[derive(Clone, Debug)]
pub struct QcdmlParticipant {
    /// ORCID identifier (e.g. "0000-0001-2345-6789"), if available.
    pub orcid: Option<String>,
    /// Full name.
    pub name: String,
    /// Institution/affiliation.
    pub institution: String,
}

/// License specification for QCDml ensemble metadata.
#[derive(Clone, Debug)]
pub struct QcdmlLicense {
    /// License name (e.g. "CC-BY-4.0").
    pub name: String,
    /// License URI (e.g. "https://creativecommons.org/licenses/by/4.0/").
    pub uri: String,
    /// Optional embargo end date (ISO 8601).
    pub embargo_end: Option<String>,
    /// Optional acknowledgment text.
    pub acknowledgment: Option<String>,
}

impl Default for QcdmlLicense {
    fn default() -> Self {
        Self {
            name: "CC-BY-4.0".to_string(),
            uri: "https://creativecommons.org/licenses/by/4.0/".to_string(),
            embargo_end: None,
            acknowledgment: Some(
                "Data generated by hotSpring-barracuda. Please cite the ensemble generation paper."
                    .to_string(),
            ),
        }
    }
}

/// Extended ensemble metadata for QCDml 2.0 compliance.
#[derive(Clone, Debug)]
pub struct QcdmlEnsembleInfo {
    /// Persistent URI for this Markov chain.
    pub markov_chain_uri: String,
    /// Collaboration name.
    pub collaboration: String,
    /// Project name.
    pub project_name: String,
    /// Ensemble label (optional human-readable tag).
    pub ensemble_label: Option<String>,
    /// License for data sharing.
    pub license: QcdmlLicense,
    /// Who generated the data.
    pub participant: QcdmlParticipant,
    /// Whether reweighting factors are needed for this ensemble.
    pub reweighting_needed: bool,
    /// Funding references (list of (funder, award) pairs).
    pub funding: Vec<(String, Option<String>)>,
}

impl QcdmlEnsembleInfo {
    /// Create default info for a hotSpring ensemble.
    pub fn for_manifest(manifest: &EnsembleManifest) -> Self {
        let [nx, ny, nz, nt] = manifest.dims;
        Self {
            markov_chain_uri: format!(
                "urn:hotspring:ensemble:{}",
                manifest.ensemble_id
            ),
            collaboration: "hotSpring".to_string(),
            project_name: "hotSpring-barracuda QCD".to_string(),
            ensemble_label: Some(format!(
                "{}x{}x{}x{} b{:.2} Nf={}",
                nx, ny, nz, nt, manifest.beta, manifest.nf
            )),
            license: QcdmlLicense::default(),
            participant: QcdmlParticipant {
                orcid: None,
                name: "hotSpring Engine".to_string(),
                institution: "ecoPrimals".to_string(),
            },
            reweighting_needed: false,
            funding: Vec::new(),
        }
    }
}

/// Extended config metadata for QCDml 2.0 compliance.
#[derive(Clone, Debug)]
pub struct QcdmlConfigInfo {
    /// Machine name where the config was generated.
    pub machine_name: String,
    /// Institution operating the machine.
    pub machine_institution: String,
    /// Machine type (e.g. "workstation", "HPC cluster").
    pub machine_type: String,
    /// Code name.
    pub code_name: String,
    /// Code version.
    pub code_version: String,
    /// Markov chain series label (e.g. "a" for the first stream).
    pub series: String,
    /// ILDG CRC checksum of the binary payload (GNU cksum algorithm).
    pub ildg_crc: Option<u32>,
}

impl QcdmlConfigInfo {
    /// Create default config info from provenance.
    pub fn from_provenance(prov: &Provenance) -> Self {
        Self {
            machine_name: prov.hostname.clone(),
            machine_institution: "ecoPrimals".to_string(),
            machine_type: if prov.gpu.is_some() {
                "GPU workstation".to_string()
            } else {
                "CPU workstation".to_string()
            },
            code_name: "hotSpring-barracuda".to_string(),
            code_version: prov.engine.clone(),
            series: "a".to_string(),
            ildg_crc: None,
        }
    }
}

/// Generate a QCDml 2.0 ensemble XML document.
pub fn generate_ensemble_xml(
    manifest: &EnsembleManifest,
    info: &QcdmlEnsembleInfo,
) -> String {
    let [nx, ny, nz, nt] = manifest.dims;
    let now = super::measurement::iso8601_now();

    let mut xml = String::with_capacity(4096);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<markovChain xmlns="http://www.lqcd.org/ildg/QCDml/ensemble2.0""#);
    xml.push_str(r#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance""#);
    xml.push_str(r#" xsi:schemaLocation="http://www.lqcd.org/ildg/QCDml/ensemble2.0 QCDmlEnsemble2.0.0.xsd">"#);
    xml.push('\n');

    // markovChainURI
    emit_tag(&mut xml, 1, "markovChainURI", &info.markov_chain_uri);

    // management
    xml.push_str("  <management>\n");
    emit_tag(&mut xml, 2, "collaboration", &info.collaboration);
    emit_tag(&mut xml, 2, "projectName", &info.project_name);
    if let Some(ref label) = info.ensemble_label {
        emit_tag(&mut xml, 2, "ensembleLabel", label);
    }
    xml.push_str("    <archiveHistory>\n");
    xml.push_str("      <archiveEvent>\n");
    emit_tag(&mut xml, 4, "revisionAction", "generate");
    emit_participant_xml(&mut xml, 4, &info.participant);
    emit_tag(&mut xml, 4, "date", &now);
    xml.push_str("      </archiveEvent>\n");
    xml.push_str("    </archiveHistory>\n");
    xml.push_str("  </management>\n");

    // license
    xml.push_str("  <license>\n");
    xml.push_str("    <standardLicense>\n");
    emit_tag(&mut xml, 3, "name", &info.license.name);
    emit_tag(&mut xml, 3, "uri", &info.license.uri);
    xml.push_str("    </standardLicense>\n");
    if let Some(ref embargo) = info.license.embargo_end {
        emit_tag(&mut xml, 2, "embargoEndDate", embargo);
    }
    if let Some(ref ack) = info.license.acknowledgment {
        xml.push_str("    <acknowledgments>\n");
        emit_tag(&mut xml, 3, "templateText", ack);
        xml.push_str("    </acknowledgments>\n");
    }
    xml.push_str("  </license>\n");

    // funding
    if !info.funding.is_empty() {
        xml.push_str("  <fundingReferences>\n");
        for (funder, award) in &info.funding {
            xml.push_str("    <fundingReference>\n");
            emit_tag(&mut xml, 3, "funderName", funder);
            if let Some(a) = award {
                emit_tag(&mut xml, 3, "awardNumber", a);
            }
            xml.push_str("    </fundingReference>\n");
        }
        xml.push_str("  </fundingReferences>\n");
    }

    // physics
    xml.push_str("  <physics>\n");
    xml.push_str("    <size>\n");
    emit_tag(&mut xml, 3, "elem", &nx.to_string());
    emit_tag(&mut xml, 3, "elem", &ny.to_string());
    emit_tag(&mut xml, 3, "elem", &nz.to_string());
    emit_tag(&mut xml, 3, "elem", &nt.to_string());
    xml.push_str("    </size>\n");

    // gauge action
    emit_gauge_action_xml(&mut xml, manifest);

    // fermion action (if dynamical)
    if manifest.nf > 0 {
        emit_fermion_action_xml(&mut xml, manifest);
    }

    xml.push_str("  </physics>\n");

    // algorithm
    emit_algorithm_xml(&mut xml, &manifest.algorithm, info.reweighting_needed);

    xml.push_str("</markovChain>\n");
    xml
}

/// Generate a QCDml 2.0 config XML document.
pub fn generate_config_xml(
    entry: &ConfigEntry,
    meta: &IldgMetadata,
    ensemble_info: &QcdmlEnsembleInfo,
    config_info: &QcdmlConfigInfo,
) -> String {
    let now = super::measurement::iso8601_now();

    let mut xml = String::with_capacity(2048);
    xml.push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
    xml.push('\n');
    xml.push_str(r#"<gaugeConfiguration xmlns="http://www.lqcd.org/ildg/QCDml/config2.0""#);
    xml.push_str(r#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance""#);
    xml.push_str(r#" xsi:schemaLocation="http://www.lqcd.org/ildg/QCDml/config2.0 QCDmlConfig2.0.0.xsd">"#);
    xml.push('\n');

    // dataLFN
    emit_tag(&mut xml, 1, "dataLFN", &entry.ildg_lfn);

    // management
    xml.push_str("  <management>\n");
    xml.push_str("    <archiveHistory>\n");
    xml.push_str("      <archiveEvent>\n");
    emit_tag(&mut xml, 4, "revisionAction", "generate");
    emit_participant_xml(&mut xml, 4, &ensemble_info.participant);
    emit_tag(&mut xml, 4, "date", &now);
    xml.push_str("      </archiveEvent>\n");
    xml.push_str("    </archiveHistory>\n");
    xml.push_str("  </management>\n");

    // implementation
    xml.push_str("  <implementation>\n");
    xml.push_str("    <machine>\n");
    emit_tag(&mut xml, 3, "name", &config_info.machine_name);
    emit_tag(&mut xml, 3, "institution", &config_info.machine_institution);
    emit_tag(&mut xml, 3, "machineType", &config_info.machine_type);
    xml.push_str("    </machine>\n");
    xml.push_str("    <code>\n");
    emit_tag(&mut xml, 3, "name", &config_info.code_name);
    emit_tag(&mut xml, 3, "version", &config_info.code_version);
    emit_tag(&mut xml, 3, "date", &now);
    xml.push_str("    </code>\n");
    xml.push_str("  </implementation>\n");

    // algorithm (empty parameters for now)
    xml.push_str("  <algorithm>\n");
    xml.push_str("    <parameters/>\n");
    xml.push_str("  </algorithm>\n");

    // precision
    let prec = if meta.precision_bits == 32 {
        "single"
    } else {
        "double"
    };
    emit_tag(&mut xml, 1, "precision", prec);

    // markovSequence
    xml.push_str("  <markovSequence>\n");
    emit_tag(&mut xml, 2, "markovChainURI", &ensemble_info.markov_chain_uri);
    emit_tag(&mut xml, 2, "series", &config_info.series);
    xml.push_str("    <markovStep>\n");
    emit_tag(&mut xml, 3, "update", &entry.trajectory.to_string());
    xml.push_str("      <record>\n");
    emit_tag(&mut xml, 4, "field", "su3gauge");
    if let Some(ref crc_str) = entry.checksum_crc32 {
        emit_tag(&mut xml, 4, "crcCheckSum", crc_str);
    } else if let Some(crc) = config_info.ildg_crc {
        emit_tag(&mut xml, 4, "crcCheckSum", &format!("{crc}"));
    }
    emit_tag(
        &mut xml,
        4,
        "avePlaquette",
        &format!("{:.15e}", entry.plaquette),
    );
    xml.push_str("      </record>\n");
    xml.push_str("    </markovStep>\n");
    xml.push_str("  </markovSequence>\n");

    xml.push_str("</gaugeConfiguration>\n");
    xml
}

fn emit_tag(xml: &mut String, indent: usize, tag: &str, value: &str) {
    for _ in 0..indent {
        xml.push_str("  ");
    }
    xml.push('<');
    xml.push_str(tag);
    xml.push('>');
    xml.push_str(&xml_escape(value));
    xml.push_str("</");
    xml.push_str(tag);
    xml.push_str(">\n");
}

fn emit_participant_xml(xml: &mut String, indent: usize, p: &QcdmlParticipant) {
    let pad = "  ".repeat(indent);
    xml.push_str(&format!("{pad}<participant>\n"));
    if let Some(ref orcid) = p.orcid {
        emit_tag(xml, indent + 1, "orcid", orcid);
    }
    emit_tag(xml, indent + 1, "name", &p.name);
    emit_tag(xml, indent + 1, "institution", &p.institution);
    xml.push_str(&format!("{pad}</participant>\n"));
}

fn emit_gauge_action_xml(xml: &mut String, manifest: &EnsembleManifest) {
    xml.push_str("    <gaugeAction>\n");
    match manifest.gauge_action.to_lowercase().as_str() {
        "symanzik" | "treelevel_symanzik" => {
            xml.push_str("      <treelevelSymanzikGluon>\n");
            xml.push_str("        <gluonField>\n");
            emit_tag(xml, 5, "group", "su3");
            emit_tag(xml, 5, "representation", "fundamental");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("        </gluonField>\n");
            emit_tag(xml, 4, "beta", &format!("{:.6}", manifest.beta));
            xml.push_str("      </treelevelSymanzikGluon>\n");
        }
        _ => {
            xml.push_str("      <wilsonGluon>\n");
            xml.push_str("        <gluonField>\n");
            emit_tag(xml, 5, "group", "su3");
            emit_tag(xml, 5, "representation", "fundamental");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("        </gluonField>\n");
            emit_tag(xml, 4, "beta", &format!("{:.6}", manifest.beta));
            xml.push_str("      </wilsonGluon>\n");
        }
    }
    xml.push_str("    </gaugeAction>\n");
}

fn emit_fermion_action_xml(xml: &mut String, manifest: &EnsembleManifest) {
    xml.push_str("    <quarkAction>\n");
    match manifest.fermion_action.to_lowercase().as_str() {
        "hisq" => {
            xml.push_str("      <hisqQuark>\n");
            xml.push_str("        <quarkField>\n");
            emit_tag(xml, 5, "normalisation", "default");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>antiperiodic</boundaryCondition>\n");
            xml.push_str("        </quarkField>\n");
            emit_tag(xml, 4, "mass", &format!("{:.6}", manifest.mass));
            emit_tag(xml, 4, "numberOfFlavours", &manifest.nf.to_string());
            xml.push_str("      </hisqQuark>\n");
        }
        _ => {
            xml.push_str("      <ksQuark>\n");
            xml.push_str("        <quarkField>\n");
            emit_tag(xml, 5, "normalisation", "default");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>periodic</boundaryCondition>\n");
            xml.push_str("          <boundaryCondition>antiperiodic</boundaryCondition>\n");
            xml.push_str("        </quarkField>\n");
            emit_tag(xml, 4, "mass", &format!("{:.6}", manifest.mass));
            emit_tag(xml, 4, "numberOfFlavours", &manifest.nf.to_string());
            xml.push_str("      </ksQuark>\n");
        }
    }
    xml.push_str("    </quarkAction>\n");
}

fn emit_algorithm_xml(xml: &mut String, alg: &AlgorithmParams, reweighting: bool) {
    xml.push_str("  <algorithm>\n");
    emit_tag(xml, 2, "annotation", &format!(
        "{} with {} integrator, dt={}, n_md={}, seed={}",
        alg.algorithm, alg.integrator, alg.dt, alg.n_md_steps, alg.seed
    ));
    xml.push_str(&format!(
        "    <reweightingNeeded>{}</reweightingNeeded>\n",
        if reweighting { "true" } else { "false" }
    ));
    xml.push_str("    <parameters>\n");
    emit_parameter(xml, "algorithm", &alg.algorithm);
    emit_parameter(xml, "integrator", &alg.integrator);
    emit_parameter(xml, "dt", &alg.dt.to_string());
    emit_parameter(xml, "n_md_steps", &alg.n_md_steps.to_string());
    emit_parameter(xml, "n_therm", &alg.n_therm.to_string());
    emit_parameter(xml, "meas_interval", &alg.meas_interval.to_string());
    emit_parameter(xml, "seed", &alg.seed.to_string());
    if let Some(tol) = alg.cg_tol {
        emit_parameter(xml, "cg_tol", &format!("{tol:.2e}"));
    }
    xml.push_str("    </parameters>\n");
    xml.push_str("  </algorithm>\n");
}

fn emit_parameter(xml: &mut String, name: &str, value: &str) {
    xml.push_str("      <parameter>\n");
    emit_tag(xml, 4, "name", name);
    emit_tag(xml, 4, "value", value);
    xml.push_str("      </parameter>\n");
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

/// Compute the ILDG CRC checksum (same algorithm as GNU coreutils `cksum`).
///
/// This is the POSIX 1003.2 CRC, which differs from CRC32 (Ethernet).
/// The ILDG spec requires this specific algorithm for `crcCheckSum` fields.
pub fn ildg_crc(data: &[u8]) -> u32 {
    let mut crc: u32 = 0;
    for &byte in data {
        crc = (crc << 8) ^ CKSUM_TABLE[((crc >> 24) ^ u32::from(byte)) as usize & 0xFF];
    }
    // Fold in the length
    let mut len = data.len();
    while len > 0 {
        crc = (crc << 8) ^ CKSUM_TABLE[((crc >> 24) ^ (len as u32 & 0xFF)) as usize & 0xFF];
        len >>= 8;
    }
    !crc
}

/// POSIX CRC lookup table (polynomial 0x04C11DB7).
#[rustfmt::skip]
static CKSUM_TABLE: [u32; 256] = {
    let mut table = [0u32; 256];
    let poly: u32 = 0x04C1_1DB7;
    let mut i = 0;
    while i < 256 {
        let mut crc = (i as u32) << 24;
        let mut j = 0;
        while j < 8 {
            if crc & 0x8000_0000 != 0 {
                crc = (crc << 1) ^ poly;
            } else {
                crc <<= 1;
            }
            j += 1;
        }
        table[i] = crc;
        i += 1;
    }
    table
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensemble_xml_contains_required_elements() {
        let manifest = EnsembleManifest::new("test_ens", [8, 8, 8, 16], 6.0);
        let info = QcdmlEnsembleInfo::for_manifest(&manifest);
        let xml = generate_ensemble_xml(&manifest, &info);

        assert!(xml.contains("<markovChain"));
        assert!(xml.contains("<markovChainURI>"));
        assert!(xml.contains("<collaboration>hotSpring</collaboration>"));
        assert!(xml.contains("<management>"));
        assert!(xml.contains("<license>"));
        assert!(xml.contains("<physics>"));
        assert!(xml.contains("<size>"));
        assert!(xml.contains("<gaugeAction>"));
        assert!(xml.contains("<wilsonGluon>"));
        assert!(xml.contains("<beta>6.000000</beta>"));
        assert!(xml.contains("<algorithm>"));
        assert!(xml.contains("<reweightingNeeded>false</reweightingNeeded>"));
        assert!(xml.contains("</markovChain>"));
    }

    #[test]
    fn ensemble_xml_with_fermions() {
        let mut manifest = EnsembleManifest::new("dyn_ens", [8, 8, 8, 8], 5.6);
        manifest.nf = 2;
        manifest.mass = 0.1;
        manifest.fermion_action = "staggered".to_string();
        let info = QcdmlEnsembleInfo::for_manifest(&manifest);
        let xml = generate_ensemble_xml(&manifest, &info);

        assert!(xml.contains("<quarkAction>"));
        assert!(xml.contains("<ksQuark>"));
        assert!(xml.contains("<mass>0.100000</mass>"));
        assert!(xml.contains("<numberOfFlavours>2</numberOfFlavours>"));
    }

    #[test]
    fn config_xml_contains_required_elements() {
        let manifest = EnsembleManifest::new("cfg_test", [4, 4, 4, 4], 6.0);
        let entry = ConfigEntry {
            trajectory: 100,
            filename: "conf_000100.lime".to_string(),
            ildg_lfn: "/hotspring/b6.0/4x4x4x4/conf.000100".to_string(),
            checksum_crc32: Some("abcd1234".to_string()),
            checksum_ildg_crc: Some(123456789),
            plaquette: 0.598,
        };
        let meta = IldgMetadata {
            dims: [4, 4, 4, 4],
            beta: 6.0,
            mass: 0.0,
            nf: 0,
            action: "Wilson".to_string(),
            fermion_action: "none".to_string(),
            creator: "test".to_string(),
            ensemble_id: "cfg_test".to_string(),
            trajectory: 100,
            plaquette: 0.598,
            precision_bits: 64,
            lfn: "/hotspring/b6.0/4x4x4x4/conf.000100".to_string(),
        };
        let ens_info = QcdmlEnsembleInfo::for_manifest(&manifest);
        let cfg_info = QcdmlConfigInfo::from_provenance(&manifest.provenance);
        let xml = generate_config_xml(&entry, &meta, &ens_info, &cfg_info);

        assert!(xml.contains("<gaugeConfiguration"));
        assert!(xml.contains("<dataLFN>"));
        assert!(xml.contains("<implementation>"));
        assert!(xml.contains("<machine>"));
        assert!(xml.contains("<code>"));
        assert!(xml.contains("<precision>double</precision>"));
        assert!(xml.contains("<markovSequence>"));
        assert!(xml.contains("<update>100</update>"));
        assert!(xml.contains("<field>su3gauge</field>"));
        assert!(xml.contains("<avePlaquette>"));
        assert!(xml.contains("</gaugeConfiguration>"));
    }

    #[test]
    fn ildg_crc_empty() {
        let crc = ildg_crc(&[]);
        assert!(crc > 0, "CRC of empty data should be nonzero: {crc}");
    }

    #[test]
    fn ildg_crc_known_value() {
        // GNU cksum of "123456789" is 930766865 9
        let data = b"123456789";
        let crc = ildg_crc(data);
        assert_eq!(crc, 930_766_865, "POSIX CRC of '123456789' should be 930766865, got {crc}");
    }

    #[test]
    fn xml_escape_special_chars() {
        assert_eq!(xml_escape("a<b>c&d"), "a&lt;b&gt;c&amp;d");
        assert_eq!(xml_escape("hello"), "hello");
    }
}
